messages:
  commands-prefix: 'chatroom' # /prefix:chatroom command, example: prefix = "rooms" - /rooms:chatroom command
  commands-invalid-usage: '&cНеверное использование!'
  commands-player-only: '&cЭта команда только для игроков!'
  commands-player-not-found: '&cЭтот игрок не найден.'

  # Only minimessage!!! https://docs.advntr.dev/minimessage/format.html
  successful-reload: '<green>Вся локализация плагина перезапущена.'

  hub-successful-set: '<green>Хаб успешно установлен.'

  hub-dont-set: '<red>Хаб не установлен, без него плагин не будет работать!'

  room-successful-created: '<green>Успешное создание комнаты.'
  room-successful-found: '<green>Комната для вас с собеседником найдена.'
  room-error-already-exists: '<red>Эта комната уже существует.'

  start-successful-queued: '<green>Вы успешно вошли в очередь (ожидайте).'
  start-roommate-found: '<green>Собеседник найден!'

  start-error-already-in-queue: '<red>Вы уже в очереди.'
  start-error-no-rooms-available: '<red>В данный момент на сервере нету свободных комнат.'
  start-error-already-in-room: '<red>Вы уже находитесь в комнате.'

  stop-successful: '<green>Вы успешно вышли из очереди.'
  stop-users-message: '<red>Кто-то из собеседников отменил очередь, комната закрыта.'
  stop-dont-in-queue-error: '<red>Вы не можете отменить. Вы не находитесь в очереди'

configuration:
  sql:
    # MariaDB, MySQL, PostgreSQL
    driver: 'mariadb'
    use: false
    host: 'localhost:3306'
    database: 'database'
    user: 'user'
    password: 'password'